services:
  url-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATABASE_URI=${DATABASE_URI}

  url-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATABASE_URI=${DATABASE_URI}

  url-app-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATABASE_URI=${DATABASE_URI}

  caddy:
    image: caddy/caddy:2.7.3-alpine
    container_name: caddy-server
    restart: unless-stopped
    ports:
      - "8084:80"
      - "8443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
